### ISSUE TITLE
How to past from clipboard is not explained

### ISSUE THREAD

**Issue by stroobandt** [jsvine/visidata-cheat-sheet#16]
The cheat sheet explains how to copy a row or column to clipboard, but how does one paste it back to the sheet or a different sheet?

**Comment by jsvine** [comment]
Thank you for noting this, @stroobandt. I'll take your feedback into consideration when I next update the cheat sheet.

**Comment by jsvine** [comment]
Thanks again @stroobandt — I've now added a section on "Copying and pasting internally".
