### ISSUE TITLE
Translation in progress: German

### ISSUE THREAD

**Issue by tdussa** [jsvine/visidata-cheat-sheet#19]

**Comment by jsvine** [comment]
Thank you, @tdussa! On my computer, generating the PDF results in the final section ("Misc."/"Sonstiges") getting cut off:  [visidata-cheat-sheet.de.pdf](https://github.com/jsvine/visidata-cheat-sheet/files/7240200/visidata-cheat-sheet.de.pdf)

If we can trim just one line-break from the first column, I *think* it should all fit. Some potential candidates for shortening:

<img width="330" alt="Screen Shot 2021-09-27 at 9 07 08 PM" src="https://user-images.githubusercontent.com/534702/135005889-ec87c025-3540-4b99-bc5d-607097fec42b.png">
<img width="330" alt="Screen Shot 2021-09-27 at 9 07 17 PM" src="https://user-images.githubusercontent.com/534702/135005891-140f5afd-b777-4b3b-8252-d9f9c51c28c3.png">
<img width="326" alt="Screen Shot 2021-09-27 at 9 07 22 PM" src="https://user-images.githubusercontent.com/534702/135005895-06200167-f436-49d3-93dc-bfd1526d67dd.png">

Do you want to pick one to rephrase?

**Comment by tdussa** [comment]
Meh.  On my machine it all fit.  Oh well.  Please change
  »Ausgewählte Zeilen (der aktuellen Spalte) in die Zwischenablage kopieren«
to
  »Ausgewählte Zeilen (der aktuellen Spalte) in die Zwischenablage«
and see whether that does the trick.

**Comment by tdussa** [comment]
Also, just as a comment: 99.9 % of users downloading the German cheat-shee will expect it to be in A4 format.  Not sure if/how this can be handled with you particular toolchain, but.  It's obviously easy to switch over to A4 by editing the relevant line in `input/template.html`, but that'd switch the English version to A4 as well, so I think it'd be better if the page size was specified in the metadata file somehow, but not sure how to go about that.

**Comment by jsvine** [comment]
On the edit: It works! Thank you for that. The German version is now merged into `develop-core` and `master` and available here: https://jsvine.github.io/visidata-cheat-sheet/de/

On the paper size: Very interesting, thank you for noting this. I'm going to move that part of the discussion to a new issue.
