### ISSUE TITLE
Translation in progress: Italian

### ISSUE THREAD

**Issue by aborruso** [jsvine/visidata-cheat-sheet#2]

**Comment by jsvine** [comment]
Very exciting!

**Comment by aborruso** [comment]
Hi @jsvine I have my first version of here https://github.com/ondata/visidata-cheat-sheet/tree/develop-it

What should I do now?

Thank you

**Comment by jsvine** [comment]
Thanks for submitting that PR! It looks great. Moving the discussion over there for now: https://github.com/jsvine/visidata-cheat-sheet/pull/3

**Comment by jsvine** [comment]
Many thanks again, @aborruso! Your Italian translation has now been fully merged and is available here: https://jsvine.github.io/visidata-cheat-sheet/it/ 

🎉🎉🎉

**Comment by aborruso** [comment]
Wowwww, Jeremy, as usual you have had a great idea.

Thank you for all

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il mer 10 lug 2019, 13:58 Jeremy Singer-Vine <notifications@github.com> ha
scritto:
