### ISSUE TITLE
An Italian duplex version

### ISSUE THREAD

**Issue by aborruso** [jsvine/visidata-cheat-sheet#7]
Dear @jsvine a friend of mine has built the duplex version in Italian https://github.com/ondata/guidaVisiData/blob/master/testo/risorse/cheat-sheet_DaStampareFronteRetro_di_GianniVitrano.pdf

What about to add it in this repo readme??

- [English](https://jsvine.github.io/visidata-cheat-sheet/en/)
- [Spanish](https://jsvine.github.io/visidata-cheat-sheet/es/)
- [Italian](https://jsvine.github.io/visidata-cheat-sheet/it/) (by [Associazione onData](https://ondata.it/))
  - the A4 duplex version (by [Gianni Vitrano](https://twitter.com/gbvitrano))

Thank you

**Comment by aborruso** [comment]
This is the file https://github.com/ondata/guidaVisiData/blob/master/testo/risorse/cheat-sheet_DaStampareFronteRetro_di_GianniVitrano.pdf

**Comment by jsvine** [comment]
Very interesting! This looks like it was manually created, yes? Would you prefer that A4 PDFs were automatically generated? Or do you prefer the manual version, so that you can add some of the extra things (e.g., "--csv-delimiter" explanation, the onData logo, etc.)?

**Comment by aborruso** [comment]
@jsvine it was created manually by Gianni. It's the kind of contribute he can give, because he is not able to change you code and produce programmatically it.

We could add a section in the README for this kind of not automatically produced outputs, or exclude these totally and have only the official outputs.

I showed it to you, because it seems to me a nice thing and a nice consequence of your idea.

**Comment by jsvine** [comment]
Thanks, @aborruso. I have now added an "Other versions" section, with Gianni's A4 as the first example: https://github.com/jsvine/visidata-cheat-sheet/commit/01b7bccea84d67b2ffea6bfaf7d9c8671e376eb8

**Comment by aborruso** [comment]
thank you @jsvine !
